mpi-launch:
  launcher: mpirun
  allow-run-as-root: auto
  export-env:
    - LD_LIBRARY_PATH
  bind-to: core
  map-by: ppr:1:l3cache
  mca:
    btl: ^tcp,ofi,vader,openib
    pml: ^ucx
    mtl: ofi
    opal_common_ofi_provider_include: shm+cxi:linkx

backends:
  tnqvm:
    wrapper: gpuwrapper.sh
  nwqsim:
    wrapper: null
  qiskitaer:
    wrapper: gpuwrapper.sh
  qtensor:
    wrapper: gpuwrapper.sh
